language: node_js

node_js:
  - 8
  - 10

branches:
  only:
    - master
    - /^greenkeeper.*$/
    - /^v[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node: 10
    repo: "${TRAVIS_REPO_SLUG}"
    tags: true
